
class CompleteColorScheme {
  final Map<String, dynamic> light;
  final Map<String, dynamic> dark;

  const CompleteColorScheme({required this.light, required this.dark});
}

final completeColorScheme = CompleteColorScheme(
  light: {
    "Primary": {
      "Main": "#39608f",
      "On Main": "#ffffff",
      "Dark": "#001c38",
      "Light": "#d3e4ff",
      "Contrast": "#000915",
      "Primary Fixed": "#d3e4ff",
      "On Primary Fixed": "#001c38",
      "Primary Fixed Dim": "#a2c9fe",
      "On Primary Fixed Variant": "#1d4875",
      "Inverse Primary": "#a2c9fe",
    },
    "Secondary": {
      "Main": "#545f70",
      "On Main": "#ffffff",
      "Dark": "#12202d",
      "Light": "#d8e6f3",
      "Contrast": "#000c18",
      "Secondary Fixed": "#d7e3f8",
      "On Secondary Fixed": "#101c2b",
      "Secondary Fixed Dim": "#bbc7db",
      "On Secondary Fixed Variant": "#3c4858",
    },
    "Schemes": {
      "Surface": "#f9f9ff",
      "Surface Variant": "#dfe2eb",
      "On Surface": "#1a1b20",
      "On Surface Variant": "#43474e",
      "Inverse Surface": "#2f3036",
      "Inverse On Surface": "#f0f0f7",
      "Outline": "#73777f",
      "Outline Variant": "#c3c6cf",
      "Background": "#f8f9ff",
      "On Background": "#191c20",
    },
    "Surface": {
      "Surface Dim": "#d0d4e3",
      "Surface Bright": "#f7f8ff",
      "Surface Container Lowest": "#ffffff",
      "Surface Container Low": "#f0f2fb",
      "Surface Container": "#e9ebf5",
      "Surface Container High": "#e2e4f1",
      "Surface Container Highest": "#dadfeb",
    },
    "Supporting": {
      "Magenda": {
        "Main": "#8c4a5f",
        "On Main": "#ffffff",
        "Dark": "#3a071c",
        "Light": "#ffd9e2",
        "Contrast": "#160209",
      },
      "Brown": {
        "Main": "#795548",
        "On Main": "#ffffff",
        "Dark": "#381407",
        "Light": "#fedacd",
        "Contrast": "#160600",
      },
      "Blue Grey": {
        "Main": "#486573",
        "On Main": "#ffffff",
        "Dark": "#072432",
        "Light": "#cdeaf8",
        "Contrast": "#000d14",
      },
      "Purple": {
        "Main": "#8d3b9b",
        "On Main": "#ffffff",
        "Dark": "#44004f",
        "Light": "#f9d3ff",
        "Contrast": "#17001b",
      },
      "Green": {
        "Main": "#47703e",
        "On Main": "#ffffff",
        "Dark": "#082d00",
        "Light": "#ccf5c3",
        "Contrast": "#031000",
      },
      "Pink": {
        "Main": "#bc2e5e",
        "On Main": "#ffffff",
        "Dark": "#56001d",
        "Light": "#ffdde9",
        "Contrast": "#1e000a",
      },
      "Tourkish": {
        "Main": "#1a7a7e",
        "On Main": "#ffffff",
        "Dark": "#00292b",
        "Light": "#a8fcff",
        "Contrast": "#000e0f",
      },
      "Yellow": {
        "Main": "#825d00",
        "On Main": "#ffffff",
        "Dark": "#281d00",
        "Light": "#ffe29b",
        "Contrast": "#0e0a00",
      },
      "Orange": {
        "Main": "#9d4f00",
        "On Main": "#ffffff",
        "Dark": "#301900",
        "Light": "#ffddb9",
        "Contrast": "#110800",
      },
    },
    "Error": {
      "Main": "#c33a10",
      "On Main": "#ffffff",
      "Dark": "#421000",
      "Light": "#ffd9cd",
      "Contrast": "#170500",
    },
  },
  dark: {
    "Primary": {
      "Main": "#a2c9fe",
      "On Main": "#00315b",
      "Dark": "#d3e4ff",
      "Light": "#1d4875",
      "Contrast": "#e8f4ff",
      "Primary Fixed": "#d3e4ff",
      "On Primary Fixed": "#001c38",
      "Primary Fixed Dim": "#a2c9fe",
      "On Primary Fixed Variant": "#1d4875",
      "Inverse Primary": "#39608f",
    },
    "Secondary": {
      "Main": "#bbc7db",
      "On Main": "#263141",
      "Dark": "#d7e3f8",
      "Light": "#3b4956",
      "Contrast": "#e9f4ff",
      "Secondary Fixed": "#d7e3f8",
      "On Secondary Fixed": "#101c2b",
      "Secondary Fixed Dim": "#bbc7db",
      "On Secondary Fixed Variant": "#3c4858",
    },
    "Schemes": {
      "Surface": "#111318",
      "Surface Variant": "#43474e",
      "On Surface": "#e2e2e9",
      "On Surface Variant": "#c3c6cf",
      "Inverse Surface": "#e2e2e9",
      "Inverse On Surface": "#2f3036",
      "Outline": "#8d9199",
      "Outline Variant": "#43474e",
      "Background": "#111418",
      "On Background": "#e1e2e8",
    },
    "Surface": {
      "Surface Dim": "#00091b",
      "Surface Bright": "#142944",
      "Surface Container Lowest": "#000615",
      "Surface Container Low": "#000e23",
      "Surface Container": "#001129",
      "Surface Container High": "#071b34",
      "Surface Container Highest": "#10253f",
    },
    "Supporting": {
      "Magenda": {
        "Main": "#ffb1c7",
        "On Main": "#541d31",
        "Dark": "#ffd9e2",
        "Light": "#703348",
        "Contrast": "#ffecf3",
      },
      "Brown": {
        "Main": "#e1bdb0",
        "On Main": "#4c281b",
        "Dark": "#fedacd",
        "Light": "#613d30",
        "Contrast": "#ffede7",
      },
      "Blue Grey": {
        "Main": "#b0cddb",
        "On Main": "#1b3846",
        "Dark": "#cdeaf8",
        "Light": "#304d5b",
        "Contrast": "#e5f6ff",
      },
      "Purple": {
        "Main": "#f2a5ff",
        "On Main": "#600e6e",
        "Dark": "#f9d3ff",
        "Light": "#752383",
        "Contrast": "#fceaff",
      },
      "Green": {
        "Main": "#afd8a6",
        "On Main": "#1a4311",
        "Dark": "#ccf5c3",
        "Light": "#2f5826",
        "Contrast": "#e1ffda",
      },
      "Pink": {
        "Main": "#ffa9c6",
        "On Main": "#8f0131",
        "Dark": "#ffd5e3",
        "Light": "#a41646",
        "Contrast": "#ffebf2",
      },
      "Tourkish": {
        "Main": "#82e2e6",
        "On Main": "#004648",
        "Dark": "#a8fcff",
        "Light": "#026266",
        "Contrast": "#d7fdff",
      },
      "Yellow": {
        "Main": "#ffc433",
        "On Main": "#443000",
        "Dark": "#ffe29b",
        "Light": "#614500",
        "Contrast": "#fff2d0",
      },
      "Orange": {
        "Main": "#ffb971",
        "On Main": "#522900",
        "Dark": "#ffddb9",
        "Light": "#753b00",
        "Contrast": "#ffefdf",
      },
    },
    "Error": {
      "Main": "#ffb199",
      "On Main": "#601410",
      "Dark": "#ffd9cd",
      "Light": "#a02500",
      "Contrast": "#ffede8",
    },
  },
);



