// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpa5Vq-7875Niuv4DWuUS7A1QrsXYtOoQ',
    appId: '1:502485495614:web:d1d910cf62b0351069c66f',
    messagingSenderId: '502485495614',
    projectId: 'eluthozhi',
    authDomain: 'eluthozhi.firebaseapp.com',
    storageBucket: 'eluthozhi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpL2tDg_GYb17-dxYIpA8uVLqdOVQPsnM',
    appId: '1:502485495614:android:f6b990b774bc5ed469c66f',
    messagingSenderId: '502485495614',
    projectId: 'eluthozhi',
    storageBucket: 'eluthozhi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLVGmyR06DOkrfJZFEwhL2QXq0vBvYF34',
    appId: '1:502485495614:ios:d0af1211c35ed10b69c66f',
    messagingSenderId: '502485495614',
    projectId: 'eluthozhi',
    storageBucket: 'eluthozhi.firebasestorage.app',
    androidClientId: '502485495614-abfvhkt0gle921mp2jdfall61jj5d4ig.apps.googleusercontent.com',
    iosClientId: '502485495614-hkhc033bnta7u039fcak1nbpsuhp7im9.apps.googleusercontent.com',
    iosBundleId: 'com.example.eluthozhiV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLVGmyR06DOkrfJZFEwhL2QXq0vBvYF34',
    appId: '1:502485495614:ios:d0af1211c35ed10b69c66f',
    messagingSenderId: '502485495614',
    projectId: 'eluthozhi',
    storageBucket: 'eluthozhi.firebasestorage.app',
    androidClientId: '502485495614-abfvhkt0gle921mp2jdfall61jj5d4ig.apps.googleusercontent.com',
    iosClientId: '502485495614-hkhc033bnta7u039fcak1nbpsuhp7im9.apps.googleusercontent.com',
    iosBundleId: 'com.example.eluthozhiV3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtBBaqXINsv_9ihmFMX3K-xDdfZWGuRrE',
    appId: '1:502485495614:web:cb9f03086f331a6a69c66f',
    messagingSenderId: '502485495614',
    projectId: 'eluthozhi',
    authDomain: 'eluthozhi.firebaseapp.com',
    storageBucket: 'eluthozhi.firebasestorage.app',
  );
}
